- package.json
- src/extension.ts
Details are given [here](https://github.com/lf-lang/lingua-franca/pull/813).
> Handle build result

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for patch version bump.
> Prepare release of v0.1.1

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.2.0.
> Prepare release of v0.2.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.3.0.
> Release of v0.3.0

- package.json
> Fix to npm `clean` script

- src/build_lds.ts
This prevents a situation where the jar used in the extension is incomplete, which causes internal errors.
> Exit when unable to checkout lingua-franca and its submodules

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.3.1.
> Release of v0.3.1

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.4.0.
> Release of v0.4.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.4.1.
> Release of v0.4.1

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.4.2.
> Release of v0.4.2

- .github/actions/build/action.yml
- .github/workflows/nightly.yml
- package.json
Nightly releases must be built using the `--pre-release` flag.
> Ability to create pre-release package

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.5.1.
> Release version v0.5.1

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.6.0.
> Release version v0.6.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.7.0.
> Release version v0.7.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.7.1.
> Release version v0.7.1

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.7.3.
> Release version v0.7.3

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.8.0.
> Release version v0.8.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.8.1.
> Release version v0.8.1

- package.json
This fixes the problem that we discussed a few minutes ago.
> Delete stale build directory

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.8.2.
> Release version v0.8.2

- README.md
This PR updates the `README.md` file to align with the latest changes made to the user interface. The modifications include:
- Enhanced clarity and organization of information related to the new Package Explorer.
- Updated sections to accurately reflect the current functionality and features.
- Improved overall readability and user engagement.
These changes aim to provide users with an up-to-date reference as they navigate the updated interface.
> Updated README to reflect recent UI changes

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.10.0.
> Release version v0.10.0

- CHANGELOG.md
- package-lock.json
- package.json
Automated pull request for bump to version 0.10.1.
> Release version v0.10.1
