lf-lang/vscode-lingua-franca

.github/actions/build-env/action.yml, .github/workflows/ci.yml, src/config.ts
Changes in PR:
- use Java 17 to build the language server
- fix the detection of the java compiler version on macOS
=> Bump to Java 17 and allow building on Mac

src/extension.ts
This changes the working directory before running any commands. Unfortunately there is no way to check if the user has changed to a different working directory, so this action will be performed unconditionally when the "Build and Run" action is triggered.
The request was to use absolute paths instead of relative paths. This does not do that because this method was easier to implement, and because it might be more robust if we have run commands that behave differently according to the current working directory. If we really want absolute paths, then that is no problem, but it would just take some more testing and changes in the `lingua-franca` main repo.
=> Make "Build and Run" action work irrespective of current working directory

.gitignore, .vscodeignore, src/extension.ts
This change makes it easier to find textual output from the language server. It should allow VS Code users to receive most of the same information that is available from the standalone compiler. The button looks like this:
The output looks like this:
The output includes ALL messages that have been generated by the language server via `System.err` and `System.out`. This may be confusing ("where do the logs start and end?"), but it makes the implementation simple because it means we do not have to worry about what does and does not belong in the output.
[This branch in the main repo](https://github.com/lf-lang/lingua-franca/pull/1174) should be merged first.
Fixes #42.
=> Add button to view output from build

CONTRIBUTING.md, package.json
This lets one invoke the `uf.py` script using `npm run`, for anyone who prefers that.
This PR is a compromise; it resolves #23 because we have decided that there is not enough practical motivation to justify spending an afternoon to actually port `uf.py`.
=> [build] Enable invocation of uf.py via npm run

syntax/lflang.tmLanguage.json
Adds syntax highlighting for modes.
Already includes new transition keyword `history` from [LF PR #1247](https://github.com/lf-lang/lingua-franca/pull/1247), hence, only merge this PR afterwards.
=> Add syntax highlighting for modes

syntax/lflang.tmLanguage.json
Previously, import statements were not recognized by the declarative highlighter if they were preceded by whitespace.
=> Fix import statement highlighting

package.json, syntax/lflang.tmLanguage.json
This hooks the LF formatter into the VS Code extension and repairs one or two minor issues that surfaced while testing the formatter.
=> Formatting

src/build_lds.ts, src/version.ts, src/version_checker.ts
This change makes the check for Java 17 less strict and also permits newer versions.
=> Support for Java versions > 17

.vscode/launch.json, src/build_lds.ts, src/config.ts, src/extension.ts
Requires [PR #1469 in LF](https://github.com/lf-lang/lingua-franca/pull/1469)
Uses the new Gradle build built the LDS jar.
Special handling of SWT library is no longer necessary and removed.
=> Switched to Gradle for language and diagram server build

src/build_commands.ts
Added escape of path in change directory command.
This fixes errors caused by paths containing a space.
=> Fix "Build and Run" command with paths that contain spaces

.github/actions/build/action.yml, .github/workflows/ci.yml, .github/workflows/dependency-tests.yml, src/config.ts
The dependency tests fail more often than not and pertain to code that has not been modified in a long time, so we should run them selectively.
=> Run dependency tests only if relevant files change

package-lock.json, package.json
Upgrade necessary to be able to use VS Code's pre-release option:
> Pre-release extensions are supported after VS Code version 1.63.0 and so all pre-release extensions needs to set engines.vscode value in their package.json to >= 1.63.0.
=> VS code engine bumped to `1.63.0`

.github/actions/build/action.yml, .github/workflows/build.yml, .github/workflows/dependency-tests.yml, src/check_dependencies.ts, src/test/check_dependencies.test.ts, src/version_checker.ts
This is mostly relevant to packages managed by NVM, which seem to be located in a special place.
Fixes #119. This does not actually fix the PATH, but it does at least update the error message so that the message suggests the correct solution and is not misleading.
I believe that we can fix the PATH if we really want to by doing some hacking with the embedded terminal. However, I anticipate that such a solution would cause bugs and maintainability problems that I do not want to face right now.
=> Update message for missing dependencies

.github/workflows/nightly.yml
Also adds the capability of producing an artifact for inspection in "dry run" mode, which is retained for 3 days.
=> Small fixes to the nightly build workflow

CHANGELOG.md, package-lock.json, package.json
Automated pull request for bump to version 0.5.0.
=> Release version v0.5.0

.github/workflows/nightly.yml
Change follow the same approach as what is done in https://github.com/lf-lang/epoch.
- Push to `latest` branch
- Tag with `nightly` tag
- Create nightly release
Fixes #56.
=> Updated nightly workflow to tag and publish release on GitHub

package-lock.json, package.json
...as suggested by `npm`. This also bumps `vsce` to `2.21.0`.
=> Package `vsce` renamed to `@vscode/vsce`

.github/actions/build/action.yml
The action ATiltedTree/setup-rust disappeared overnight. This PR switches to another action.
=> Fix rust setup action in CI

package.json
This adds a necessary compilation step to the `vscode:prepublish` task.
=> Fix prepublish task

CONTRIBUTING.md, package.json
I added a recommended npm version. If you are using a different one, please correct me.
Instead of only an install command, I updated the guide and split the install command install and installExtension.
I updated the debugging guide for the VS Code + IntelliJ combination on the VS Code side.
Note that splitting the install command might be annoying for several users that previously used it to install the extension, maybe the `npm install && npm run installExtension` command should be also put in the readme?
Maybe we should also add why Rust is necessary to build this.
=> Updated contributing guide to include the debugging workflow.

package.json, src/extension.ts, src/lfview/lf-data-provider-commands.ts, src/lfview/lf-data-provider.ts
This PR fixes the action that navigates to the project’s `Lingo.toml` and removes an unused command.
=> Resolve goToLingoToml for Windows

package.json
This PR updates the link in the error message when a project doesn’t comply with the correct Lingua Franca project structure. This allows developers to directly click the link and access the relevant documentation for more information.
=> Update documentation link

.github/scripts/nightly-version.sh
Fixes #170. To be merged on the day that `v0.9.0` is published.
=> Adjustment of version numbers for nightly releases

CHANGELOG.md, package-lock.json, package.json
Automated pull request for bump to version 0.9.0.
=> Release version v0.9.0
